version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Utiliza la versi贸n de Node.js 20.9.0
    commands:
      - npm install -g @angular/cli  # Instala Angular CLI de forma global
      - npm install  # Instala las dependencias del proyecto

  pre_build:
    commands:
      - ng build --prod  # Construye la aplicaci贸n Angular para producci贸n

artifacts:
  files:
    - '**/*'  # Incluye todos los archivos generados en la carpeta actual
  base-directory: dist/  # Especifica la carpeta donde se encuentra la aplicaci贸n compilada